### ISSUE TITLE
Spurious unecessary trailing semicolon warning

### ISSUE THREAD

**Issue by casey** [withoutboats/fehler#49] opened 2020-04-29 06:57 UTC
I'm getting a warning to remove a trailing semicolon in a trait definition, but removing it causes an error:

```
pub(crate) trait CommandExt {
  #[throws]
  fn out(&mut self) -> String;

  #[throws]
  fn status_into_result(&mut self); // <-- this semicolon triggers the warning
}
```

```
warning: unnecessary trailing semicolon
 --> bin/gen/src/command_ext.rs:8:35
  |
8 |   fn status_into_result(&mut self);
  |                                   ^ help: remove this semicolon
  |
```

**Comment by withoutboats** [comment] 2020-05-10 15:59
Closing as a duplicate of #39. #40 will fix this.

**Closed by withoutboats** 2020-05-10 15:59 UTC

**Comment by casey** [comment] 2020-05-10 19:28
Ahh, nice, I didn't see that.
